// This file was auto-generated by prisma-generator-typescript-interfaces

export interface User {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  image: string | null;
  createdAt: Date;
  updatedAt: Date;
  sessions?: Session[];
  accounts?: Account[];
  Bot?: Bot[];
  Server?: Server[];
}

export interface Session {
  id: string;
  expiresAt: Date;
  token: string;
  createdAt: Date;
  updatedAt: Date;
  ipAddress: string | null;
  userAgent: string | null;
  userId: string;
  user?: User;
}

export interface Account {
  id: string;
  accountId: string;
  providerId: string;
  userId: string;
  user?: User;
  accessToken: string | null;
  refreshToken: string | null;
  idToken: string | null;
  accessTokenExpiresAt: Date | null;
  refreshTokenExpiresAt: Date | null;
  scope: string | null;
  password: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Verification {
  id: string;
  identifier: string;
  value: string;
  expiresAt: Date;
  createdAt: Date | null;
  updatedAt: Date | null;
}

export interface Server {
  id: string;
  name: string;
  description: string | null;
  ownerId: string;
  createdAt: Date;
  updatedAt: Date;
  serverid: string | null;
  bots?: Bot[];
  owner?: User;
}

export interface Bot {
  id: string;
  name: string;
  token: string;
  active: boolean;
  ownerId: string;
  prefix: string;
  createdAt: Date;
  updatedAt: Date;
  description: string;
  tags: string[];
  icon: string | null;
  serverId: string;
  analytics?: Analytics[];
  owner?: User;
  server?: Server;
  configurations?: BotConfig[];
  commands?: Command[];
  events?: Event[];
}

export interface Command {
  id: string;
  name: string;
  description: string;
  response: string;
  enabled: boolean;
  botId: string;
  createdAt: Date;
  updatedAt: Date;
  bot?: Bot;
  permissions?: CommandPermission[];
  usage?: CommandUsage[];
}

export interface CommandPermission {
  id: string;
  commandId: string;
  roleId: string;
  allow: boolean;
  createdAt: Date;
  command?: Command;
}

export interface Event {
  id: string;
  name: string;
  action: string;
  enabled: boolean;
  botId: string;
  createdAt: Date;
  updatedAt: Date;
  bot?: Bot;
}

export interface BotConfig {
  id: string;
  key: string;
  value: string;
  botId: string;
  createdAt: Date;
  updatedAt: Date;
  bot?: Bot;
}

export interface CommandUsage {
  id: string;
  commandId: string;
  userId: string;
  guildId: string;
  channelId: string;
  timestamp: Date;
  command?: Command;
}

export interface Analytics {
  id: string;
  botId: string;
  eventType: string;
  data: JsonValue;
  timestamp: Date;
  bot?: Bot;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
