/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '../../api/services/axios.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '../../api/services/axios.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { getV1ServersQueryResponse } from '../../gen/types/servers/getServers.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getV1ServersQueryKey = () => [{ url: '/v1/servers/' }] as const

export type GetV1ServersQueryKey = ReturnType<typeof getV1ServersQueryKey>

/**
 * {@link /v1/servers/}
 */
export async function getV1Servers(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<getV1ServersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/v1/servers/`, ...requestConfig })
  return res
}

export function getV1ServersQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getV1ServersQueryKey()
  return queryOptions<ResponseConfig<getV1ServersQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<getV1ServersQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1Servers(config)
    },
  })
}

/**
 * {@link /v1/servers/}
 */
export function useGetV1Servers<
  TData = ResponseConfig<getV1ServersQueryResponse>,
  TQueryData = ResponseConfig<getV1ServersQueryResponse>,
  TQueryKey extends QueryKey = GetV1ServersQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<getV1ServersQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getV1ServersQueryKey()

  const query = useQuery(
    {
      ...(getV1ServersQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}