/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '../../api/services/axios.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '../../api/services/axios.ts'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { getV1BotsQueryResponse } from '../../gen/types/bots/getBots.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getV1BotsQueryKey = () => [{ url: '/v1/bots/' }] as const

export type GetV1BotsQueryKey = ReturnType<typeof getV1BotsQueryKey>

/**
 * {@link /v1/bots/}
 */
export async function getV1Bots(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<getV1BotsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/v1/bots/`, ...requestConfig })
  return res
}

export function getV1BotsQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getV1BotsQueryKey()
  return queryOptions<ResponseConfig<getV1BotsQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<getV1BotsQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getV1Bots(config)
    },
  })
}

/**
 * {@link /v1/bots/}
 */
export function useGetV1Bots<
  TData = ResponseConfig<getV1BotsQueryResponse>,
  TQueryData = ResponseConfig<getV1BotsQueryResponse>,
  TQueryKey extends QueryKey = GetV1BotsQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<getV1BotsQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getV1BotsQueryKey()

  const query = useQuery(
    {
      ...(getV1BotsQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}