/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '../../api/services/axios.ts'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '../../api/services/axios.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { putV1BotsBotidMutationRequest, putV1BotsBotidMutationResponse, putV1BotsBotidPathParams } from '../../gen/types/bots/putBotsBotid.ts'
import { useMutation } from '@tanstack/react-query'

export const putV1BotsBotidMutationKey = () => [{ url: '/v1/bots/{botId}' }] as const

export type PutV1BotsBotidMutationKey = ReturnType<typeof putV1BotsBotidMutationKey>

/**
 * {@link /v1/bots/:botId}
 */
export async function putV1BotsBotid(
  botId: putV1BotsBotidPathParams['botId'],
  data?: putV1BotsBotidMutationRequest,
  config: Partial<RequestConfig<putV1BotsBotidMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<putV1BotsBotidMutationResponse, ResponseErrorConfig<Error>, putV1BotsBotidMutationRequest>({
    method: 'PUT',
    url: `/v1/bots/${botId}`,
    data,
    ...requestConfig,
  })
  return res
}

/**
 * {@link /v1/bots/:botId}
 */
export function usePutV1BotsBotid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<putV1BotsBotidMutationResponse>,
      ResponseErrorConfig<Error>,
      { botId: putV1BotsBotidPathParams['botId']; data?: putV1BotsBotidMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<putV1BotsBotidMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation: { client: queryClient, ...mutationOptions } = {}, client: config = {} } = options ?? {}
  const mutationKey = mutationOptions?.mutationKey ?? putV1BotsBotidMutationKey()

  return useMutation<
    ResponseConfig<putV1BotsBotidMutationResponse>,
    ResponseErrorConfig<Error>,
    { botId: putV1BotsBotidPathParams['botId']; data?: putV1BotsBotidMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ botId, data }) => {
        return putV1BotsBotid(botId, data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}