/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '../../api/services/axios.ts'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '../../api/services/axios.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { postV1BotsStartMutationRequest, postV1BotsStartMutationResponse } from '../../gen/types/bots/postBotsStart.ts'
import { useMutation } from '@tanstack/react-query'

export const postV1BotsStartMutationKey = () => [{ url: '/v1/bots/start' }] as const

export type PostV1BotsStartMutationKey = ReturnType<typeof postV1BotsStartMutationKey>

/**
 * {@link /v1/bots/start}
 */
export async function postV1BotsStart(
  data: postV1BotsStartMutationRequest,
  config: Partial<RequestConfig<postV1BotsStartMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<postV1BotsStartMutationResponse, ResponseErrorConfig<Error>, postV1BotsStartMutationRequest>({
    method: 'POST',
    url: `/v1/bots/start`,
    data,
    ...requestConfig,
  })
  return res
}

/**
 * {@link /v1/bots/start}
 */
export function usePostV1BotsStart<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<postV1BotsStartMutationResponse>,
      ResponseErrorConfig<Error>,
      { data: postV1BotsStartMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<postV1BotsStartMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation: { client: queryClient, ...mutationOptions } = {}, client: config = {} } = options ?? {}
  const mutationKey = mutationOptions?.mutationKey ?? postV1BotsStartMutationKey()

  return useMutation<ResponseConfig<postV1BotsStartMutationResponse>, ResponseErrorConfig<Error>, { data: postV1BotsStartMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return postV1BotsStart(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}