/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '../../api/services/axios.ts'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '../../api/services/axios.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { postV1BotsStopMutationRequest, postV1BotsStopMutationResponse } from '../../gen/types/bots/postBotsStop.ts'
import { useMutation } from '@tanstack/react-query'

export const postV1BotsStopMutationKey = () => [{ url: '/v1/bots/stop' }] as const

export type PostV1BotsStopMutationKey = ReturnType<typeof postV1BotsStopMutationKey>

/**
 * {@link /v1/bots/stop}
 */
export async function postV1BotsStop(
  data: postV1BotsStopMutationRequest,
  config: Partial<RequestConfig<postV1BotsStopMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<postV1BotsStopMutationResponse, ResponseErrorConfig<Error>, postV1BotsStopMutationRequest>({
    method: 'POST',
    url: `/v1/bots/stop`,
    data,
    ...requestConfig,
  })
  return res
}

/**
 * {@link /v1/bots/stop}
 */
export function usePostV1BotsStop<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<postV1BotsStopMutationResponse>,
      ResponseErrorConfig<Error>,
      { data: postV1BotsStopMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<postV1BotsStopMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation: { client: queryClient, ...mutationOptions } = {}, client: config = {} } = options ?? {}
  const mutationKey = mutationOptions?.mutationKey ?? postV1BotsStopMutationKey()

  return useMutation<ResponseConfig<postV1BotsStopMutationResponse>, ResponseErrorConfig<Error>, { data: postV1BotsStopMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return postV1BotsStop(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}