/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '../../api/services/axios.ts'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '../../api/services/axios.ts'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { putV1BotsBotidSyncMutationResponse, putV1BotsBotidSyncPathParams } from '../../gen/types/bots/putBotsBotidSync.ts'
import { useMutation } from '@tanstack/react-query'

export const putV1BotsBotidSyncMutationKey = () => [{ url: '/v1/bots/{botId}/sync' }] as const

export type PutV1BotsBotidSyncMutationKey = ReturnType<typeof putV1BotsBotidSyncMutationKey>

/**
 * {@link /v1/bots/:botId/sync}
 */
export async function putV1BotsBotidSync(botId: putV1BotsBotidSyncPathParams['botId'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<putV1BotsBotidSyncMutationResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'PUT',
    url: `/v1/bots/${botId}/sync`,
    ...requestConfig,
  })
  return res
}

/**
 * {@link /v1/bots/:botId/sync}
 */
export function usePutV1BotsBotidSync<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<putV1BotsBotidSyncMutationResponse>,
      ResponseErrorConfig<Error>,
      { botId: putV1BotsBotidSyncPathParams['botId'] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { mutation: { client: queryClient, ...mutationOptions } = {}, client: config = {} } = options ?? {}
  const mutationKey = mutationOptions?.mutationKey ?? putV1BotsBotidSyncMutationKey()

  return useMutation<
    ResponseConfig<putV1BotsBotidSyncMutationResponse>,
    ResponseErrorConfig<Error>,
    { botId: putV1BotsBotidSyncPathParams['botId'] },
    TContext
  >(
    {
      mutationFn: async ({ botId }) => {
        return putV1BotsBotidSync(botId, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}